### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by rgwch** [sydro/docker-imapsync#2]
Thank you! Great idea to simplify the use of the Perl imapsync

Only one thing:
My version of docker (26.1.2) doesn't like this docker.compose.yml
It should be:

```
services:
  imapsync:
    build: .
    env_file:
      - imapsync.env
```

After that, it works perfectly.
